import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

import '../../../core/theme/app_theme.dart';
import '../../../core/widget/common_widgets.dart';
import '../widget/legal_sections.dart';

/// Privacy Policy screen for ECOM-PARIS LLC / Tuco app.
/// Legal copy is intentionally kept in English (single legal version).
class PrivacyPolicyScreen extends StatelessWidget {
  const PrivacyPolicyScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.background,
      appBar: const SubPageHeader(title: 'Privacy Policy'),
      body: SingleChildScrollView(
        padding: EdgeInsets.all(20.w),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text('Privacy Policy',
                style: AppTextStyles.sectionTitle.copyWith(fontSize: 24.sp)),
            SizedBox(height: 12.h),
            const LegalParagraph(
                'This Privacy Policy explains how ECOM-PARIS LLC ("we", "our", "us") collects, uses, stores, and protects your personal information when you use Tuco or related services.'),
            SizedBox(height: 24.h),
            const LegalBulletSection('1. Information We Collect', [
              'Usage data (app interactions, lesson and call usage patterns)',
              'Anonymous account information (Firebase anonymous auth)',
              'Learning progress, vocabulary and session data stored in your Firestore profile',
            ]),
            const LegalBulletSection('2. How We Use Your Information', [
              'To provide and improve conversation, lesson, and analytics features',
              'To respond to user inquiries and customer support requests',
              'To send essential updates and comply with legal obligations',
            ]),
            const LegalParagraphSection('3. Microphone and Voice Data',
                'Tuco uses your device microphone to power AI conversation practice. Your voice is processed transiently to transcribe and respond during calls; audio recordings are not retained after processing.\n\nWe do not collect, store, or retain any biometric or voice-print data.'),
            const LegalBulletSection('4. AI-Processed Data', [
              'Conversation features use third-party AI services to process your speech and generate responses and feedback',
              'Your speech and messages are processed by Google Gemini (Google LLC) to transcribe your speech and generate conversational responses. See Google\'s privacy policy at https://policies.google.com/privacy',
              'Spoken responses are generated by ElevenLabs (ElevenLabs Inc.) text-to-speech. See ElevenLabs\' privacy policy at https://elevenlabs.io/privacy-policy',
              'Data sent to these AI providers is processed only for the requested task and is not retained or reused for training',
              'No biometric data is extracted or stored during AI processing',
            ]),
            const LegalBulletSection('5. Sharing of Information', [
              'We do not sell or rent personal data',
              'We share data only with service providers (processors) who process it on our behalf and under our instructions: Google (Firebase Authentication, Cloud Firestore, and Gemini AI), ElevenLabs (text-to-speech), and Mixpanel (usage analytics)',
              'AI providers (Google Gemini, ElevenLabs) process data transiently for the requested service; Mixpanel stores usage analytics to help us improve the app. None of these providers use your data for their own purposes',
            ]),
            const LegalParagraphSection('6. Data Security',
                'We use appropriate technical and organizational measures to protect all personal data against unauthorized access, alteration, loss, or misuse.'),
            const LegalParagraphSection('7. Your Rights',
                'You may request access, correction, or deletion of your personal data by contacting us directly. We respond to all verified requests in compliance with applicable privacy laws.'),
            const LegalParagraphSection('8. Policy Updates',
                'We may update this Privacy Policy periodically. Any revisions will be posted on this page with an updated effective date.'),
            const LegalContactSection('9. Contact Us',
                'For any questions regarding this Privacy Policy, please contact:'),
            const LegalBulletSection('10. Data Deletion Requests', [
              'You can delete all your data at any time by deleting your account in the app: go to Settings and tap "Delete account"',
              'Deleting your account permanently erases all personal data associated with it (learning progress, vocabulary, call history, and streaks)',
              'Alternatively, users can request deletion of all personal data associated with their account at any time',
              'Send an email to contact@ecomparis.org with the subject "Data Deletion Request"',
              'All verified deletion requests are processed within 30 days and cannot be undone once completed',
            ]),
            SizedBox(height: 24.h),
            const LegalFooter(),
            SizedBox(height: 16.h),
          ],
        ),
      ),
    );
  }
}
